const blogPosts = [
    {
        id: 1,
        title: "7 Ways to Decorate Your Home",
        slug: "7-ways-to-decorate-your-home",
        category: "Decoration",
        tags: ["home decor", "interior design", "tips"],
        date: "2024-11-15",
        author: "Sophia Nguyen",
        authorImage: "images/author-sophia.jpg",
        readTime: 5,
        image: "images/home-decore-blog.svg",
        excerpt: "Transform your living space with these seven proven decoration techniques that bring style and comfort to every room in your home.",
        featured: true,
        content: [
            { type: "paragraph", text: "Your home is your sanctuary, and how you decorate it speaks volumes about your personality and taste. Whether you're starting fresh or looking to refresh your existing space, these seven decoration techniques will help you create a home that feels both stylish and uniquely yours." },
            { type: "heading", text: "1. Choose a Cohesive Color Palette" },
            { type: "paragraph", text: "The foundation of any well-decorated home starts with a thoughtful color palette. Choose three to five colors that work harmoniously together — a dominant color for walls, a secondary color for large furniture pieces, and accent colors for accessories and textiles." },
            { type: "heading", text: "2. Layer Your Lighting" },
            { type: "paragraph", text: "Great lighting transforms a room. Combine ambient lighting (overhead fixtures), task lighting (desk or reading lamps), and accent lighting (wall sconces or uplighters) to create depth and atmosphere in every space." },
            { type: "heading", text: "3. Mix Textures and Materials" },
            { type: "paragraph", text: "Combining different textures — smooth ceramics, rough wood, soft velvet, and metallic accents — creates visual interest and makes a room feel rich and layered. Don't be afraid to experiment with unexpected material combinations." },
            { type: "heading", text: "4. Create Focal Points" },
            { type: "paragraph", text: "Every room needs a focal point — a fireplace, a statement artwork, or a beautiful piece of furniture that draws the eye immediately upon entering. Build your decoration around this focal point for a cohesive look." },
            { type: "heading", text: "5. Add Greenery" },
            { type: "paragraph", text: "Plants breathe life into any interior. From large statement plants like fiddle-leaf figs and monstera to small succulents on shelves, greenery adds color, texture, and a connection to nature that no artificial decoration can replicate." },
            { type: "heading", text: "6. Curate Your Display Shelves" },
            { type: "paragraph", text: "Thoughtfully styled shelves can become works of art. Mix books, plants, candles, and meaningful objects. Use the rule of odd numbers — groups of three or five items tend to look more dynamic than even-numbered groupings." },
            { type: "heading", text: "7. Invest in Quality Textiles" },
            { type: "paragraph", text: "Cushions, throws, rugs, and curtains can completely transform a room's feel without major renovation. Choose textiles that are both beautiful and functional, and don't shy away from layering multiple rugs for a cozy, eclectic look." }
        ]
    },
    {
        id: 2,
        title: "Kitchen Organization: The Ultimate Guide",
        slug: "kitchen-organization-ultimate-guide",
        category: "Organization",
        tags: ["kitchen", "organization", "storage", "tips"],
        date: "2024-10-28",
        author: "Marcus Chen",
        authorImage: "images/author-marcus.jpg",
        readTime: 7,
        image: "images/kitchen-blog.svg",
        excerpt: "A well-organized kitchen isn't just beautiful — it makes cooking more enjoyable and efficient. Here's how to transform your kitchen into a perfectly organized space.",
        featured: false,
        content: [
            { type: "paragraph", text: "The kitchen is the heart of the home, and keeping it organized is key to stress-free cooking and a beautiful space. Whether you have a large kitchen or a compact one, these strategies will help you maximize every inch." },
            { type: "heading", text: "Start with a Deep Clean and Declutter" },
            { type: "paragraph", text: "Before organizing, take everything out and assess what you actually use. Donate duplicate items, toss expired food, and be honest about appliances you haven't used in a year. A lighter kitchen is easier to organize and maintain." },
            { type: "heading", text: "Zone Your Kitchen" },
            { type: "paragraph", text: "Divide your kitchen into zones based on function: cooking zone (near the stove), prep zone (near the counter), cleaning zone (near the sink), and storage zone (pantry and cabinets). Store items where you use them most." },
            { type: "heading", text: "Maximize Cabinet Space" },
            { type: "paragraph", text: "Use shelf risers to double your cabinet capacity. Store pot lids vertically using a dedicated organizer. Keep frequently used items at eye level and store rarely used items higher up or in the back." },
            { type: "heading", text: "Master the Pantry" },
            { type: "paragraph", text: "Decant dry goods into clear, airtight containers. Label everything clearly with the contents and expiration date. Group similar items together — all baking supplies, all grains, all canned goods. A Lazy Susan in corner cabinets prevents items from getting lost." },
            { type: "heading", text: "Drawer Organization" },
            { type: "paragraph", text: "Use drawer dividers for utensils and cutlery. Keep your most-used tools in the drawer closest to the stove. Dedicate one drawer to kitchen linens and another to small appliance accessories." },
            { type: "heading", text: "The Refrigerator System" },
            { type: "paragraph", text: "Assign specific zones in your fridge: dairy on the door shelves, leftovers at eye level, produce in the crisper drawers, and raw meat on the lowest shelf. Clear containers make it easy to see what you have, reducing food waste." }
        ]
    },
    {
        id: 3,
        title: "Decorate Your Bedroom Like a Pro",
        slug: "decorate-your-bedroom-like-a-pro",
        category: "Decoration",
        tags: ["bedroom", "interior design", "sleep", "cozy"],
        date: "2024-10-10",
        author: "Sophia Nguyen",
        authorImage: "images/author-sophia.jpg",
        readTime: 6,
        image: "images/bedroom-blog.svg",
        excerpt: "Your bedroom should be your ultimate sanctuary. Discover professional design secrets to create a restful, beautiful bedroom that you'll love retreating to every night.",
        featured: false,
        content: [
            { type: "paragraph", text: "The bedroom is perhaps the most personal space in your home — it's where you begin and end each day. Professional designers approach bedroom decoration with both aesthetics and function in mind, creating spaces that are as beautiful as they are restful." },
            { type: "heading", text: "Start with the Bed as Your Anchor" },
            { type: "paragraph", text: "The bed is the centerpiece of any bedroom. Invest in quality bedding — high thread-count sheets, plump pillows, and a duvet that works for your climate. Layer a throw at the foot of the bed for both style and practicality." },
            { type: "heading", text: "Consider Your Color Psychology" },
            { type: "paragraph", text: "Bedrooms benefit from calming, soothing colors. Soft blues, warm neutrals, sage greens, and lavender tones promote relaxation and better sleep. Avoid high-energy colors like bright red or orange unless used sparingly as accents." },
            { type: "heading", text: "Create a Balanced Layout" },
            { type: "paragraph", text: "Position your bed as the focal point, ideally against the main wall with space on both sides for nightstands. Maintain clear pathways around furniture. Leave at least 60cm (24 inches) of walking space on each side of the bed." },
            { type: "heading", text: "Master Bedroom Lighting" },
            { type: "paragraph", text: "Layer your lighting: use warm overhead lighting for general illumination, bedside table lamps for reading, and consider dimmable switches to adjust the mood. Blackout curtains or blinds are essential for quality sleep." },
            { type: "heading", text: "Add a Reading Nook" },
            { type: "paragraph", text: "If space allows, create a cozy reading corner with a comfortable armchair, a small side table, and a floor lamp. This dedicated relaxation zone adds character to the room and gives you a place to unwind before sleep." },
            { type: "heading", text: "Thoughtful Storage Solutions" },
            { type: "paragraph", text: "Clutter is the enemy of relaxation. Use under-bed storage for seasonal items, nightstands with drawers for bedtime essentials, and consider a bedroom bench at the foot of the bed that doubles as storage." }
        ]
    },
    {
        id: 4,
        title: "Japandi Style: The 2024 Interior Trend You Need",
        slug: "japandi-style-2024-interior-trend",
        category: "Trends",
        tags: ["japandi", "minimalism", "trends", "japanese", "scandinavian"],
        date: "2024-09-20",
        author: "Ellie Thompson",
        authorImage: "images/author-ellie.jpg",
        readTime: 8,
        image: "images/japandi-blog.jpg",
        excerpt: "Japandi — the beautiful marriage of Japanese wabi-sabi philosophy and Scandinavian hygge — is dominating interior design in 2024. Here's everything you need to know.",
        featured: true,
        content: [
            { type: "paragraph", text: "Japandi is more than just a trend — it's a lifestyle philosophy that combines the Japanese concept of wabi-sabi (finding beauty in imperfection) with the Scandinavian principle of hygge (coziness and contentment). The result is an aesthetic that is simultaneously minimalist and warm, simple yet deeply intentional." },
            { type: "heading", text: "The Core Principles of Japandi" },
            { type: "paragraph", text: "At its heart, Japandi celebrates craftsmanship, natural materials, and functional beauty. Every item in a Japandi home should serve a purpose, be beautiful in its simplicity, and feel like it belongs there — nothing is superfluous." },
            { type: "heading", text: "The Japandi Color Palette" },
            { type: "paragraph", text: "Think muted earth tones: warm whites, soft grays, warm beiges, terracotta, and deep forest greens. These colors evoke a sense of nature and calm. Avoid harsh whites or sterile grays — the palette should feel organic and warm." },
            { type: "heading", text: "Furniture and Materials" },
            { type: "paragraph", text: "Natural, unpainted wood is central to Japandi design — particularly oak, ash, and walnut in light to medium tones. Furniture features clean lines and low profiles, inspired by traditional Japanese furniture that sits close to the ground." },
            { type: "heading", text: "Textures and Textiles" },
            { type: "paragraph", text: "Natural textures are key: linen cushions, wool throws, rattan accessories, and ceramic vessels. Handmade, slightly imperfect ceramics are especially prized in Japandi design — they embody the wabi-sabi concept of embracing imperfection." },
            { type: "heading", text: "Bringing Japandi Into Your Home" },
            { type: "paragraph", text: "You don't need to redecorate from scratch. Start with small changes: replace synthetic cushions with linen ones, add a few natural wood accessories, remove clutter, and introduce a simple plant arrangement. Japandi is about intentionality, not perfection." },
            { type: "heading", text: "Japandi in Every Room" },
            { type: "paragraph", text: "In the living room, focus on a neutral sofa with natural fiber cushions and a raw wood coffee table. In the bedroom, opt for a platform bed with clean lines and linen bedding. In the kitchen, open shelving with curated ceramics and natural wood cutting boards complete the look." }
        ]
    },
    {
        id: 5,
        title: "The Art of Minimalist Living",
        slug: "the-art-of-minimalist-living",
        category: "Decoration",
        tags: ["minimalism", "declutter", "lifestyle", "simple living"],
        date: "2024-09-05",
        author: "Marcus Chen",
        authorImage: "images/author-marcus.jpg",
        readTime: 6,
        image: "images/minimalist-blog.avif",
        excerpt: "Minimalism isn't about having less — it's about making room for what truly matters. Discover how to apply minimalist principles to create a calmer, more intentional home.",
        featured: false,
        content: [
            { type: "paragraph", text: "In a world of constant stimulation and endless consumption, minimalism offers a refreshing counter-narrative: that less is genuinely more. A minimalist home isn't empty or cold — it's carefully curated to include only what you love and use, creating space for clarity and peace of mind." },
            { type: "heading", text: "The Minimalist Mindset Shift" },
            { type: "paragraph", text: "Minimalism begins not with decluttering your home but with shifting your mindset. Instead of asking 'what should I get rid of?', ask 'what do I truly value?' This positive framing makes the process of simplifying feel empowering rather than restrictive." },
            { type: "heading", text: "The One-In, One-Out Rule" },
            { type: "paragraph", text: "For every new item you bring into your home, one item leaves. This simple rule prevents the gradual accumulation of stuff that undermines minimalist living. Before every purchase, ask yourself: 'Does this add genuine value to my life?'" },
            { type: "heading", text: "Creating Visual Calm" },
            { type: "paragraph", text: "A minimalist space is defined by what you see — and what you don't see. Maximize storage to keep counters and surfaces clear. When surfaces are clear, the eye can rest and the mind follows. This is the essence of visual calm." },
            { type: "heading", text: "Curating Your Display Items" },
            { type: "paragraph", text: "The items you choose to display should be truly meaningful — a piece of art you love, a plant you care for, a beautiful object with a story. Each displayed item deserves its own space and shouldn't compete for attention." },
            { type: "heading", text: "Quality Over Quantity" },
            { type: "paragraph", text: "Minimalism often means fewer but better things. Invest in quality pieces that will last for years rather than many cheap items that need replacing. A single beautiful ceramic vase is worth more than ten mediocre decorative pieces." }
        ]
    },
    {
        id: 6,
        title: "Smart Storage Solutions for Small Spaces",
        slug: "smart-storage-solutions-small-spaces",
        category: "Organization",
        tags: ["storage", "small spaces", "organization", "DIY", "tips"],
        date: "2024-08-22",
        author: "Ellie Thompson",
        authorImage: "images/author-ellie.jpg",
        readTime: 7,
        image: "images/storage-blog.jpg",
        excerpt: "Limited square footage doesn't mean limited style. These clever storage solutions will help you make the most of every inch in your small space.",
        featured: false,
        content: [
            { type: "paragraph", text: "Small spaces challenge us to be creative and intentional about how we use every square foot. The good news? Constraints breed creativity, and there are more smart storage solutions available today than ever before." },
            { type: "heading", text: "Think Vertical" },
            { type: "paragraph", text: "When floor space is limited, go up. Floor-to-ceiling shelving, tall bookcases, and stacked storage units make use of often-overlooked vertical space. Install floating shelves at varying heights to create both storage and visual interest." },
            { type: "heading", text: "Furniture That Works Twice" },
            { type: "paragraph", text: "Multi-functional furniture is a small-space essential. Ottoman storage (use as a seat, foot rest, and hidden storage), bed frames with built-in drawers, extendable dining tables, and sofa beds are investments that earn their keep." },
            { type: "heading", text: "Under-Stair Storage" },
            { type: "paragraph", text: "The space under stairs is often wasted. Convert it into pull-out drawers, a home office nook, a mudroom with hooks and shelves, or even a small library. This is one of the most impactful storage transformations in a small home." },
            { type: "heading", text: "The Power of Hooks" },
            { type: "paragraph", text: "Hooks are the unsung heroes of small-space organization. Use them on the backs of doors (for bags, coats, and shoes), inside cabinet doors (for cleaning supplies and pot lids), in the bathroom (for towels and robes), and in the entryway." },
            { type: "heading", text: "Clear Containers and Labels" },
            { type: "paragraph", text: "In small spaces, being able to find things quickly is essential. Clear containers let you see contents at a glance, while labels mean every family member knows exactly where things belong." }
        ]
    },
    {
        id: 7,
        title: "Color Psychology in Home Decor",
        slug: "color-psychology-home-decor",
        category: "Guides",
        tags: ["color", "psychology", "decoration", "guide", "mood"],
        date: "2024-08-08",
        author: "Sophia Nguyen",
        authorImage: "images/author-sophia.jpg",
        readTime: 9,
        image: "images/color-blog.png",
        excerpt: "The colors you choose for your home affect your mood, energy, and wellbeing. Learn the science and art of using color intentionally in interior design.",
        featured: true,
        content: [
            { type: "paragraph", text: "Color is one of the most powerful tools in an interior designer's toolkit. The right colors can make a small room feel expansive, a cold space feel warm, and a hectic mind feel calm. Understanding color psychology helps you make intentional choices that support your lifestyle and wellbeing." },
            { type: "heading", text: "Understanding Color Temperature" },
            { type: "paragraph", text: "Colors are described as warm (reds, oranges, yellows) or cool (blues, greens, purples). Warm colors advance and energize — they make spaces feel smaller and cozier. Cool colors recede and calm — they make spaces feel larger and more serene." },
            { type: "heading", text: "Blue: The Universal Calm" },
            { type: "paragraph", text: "Blue is consistently rated as the world's favorite color and for good reason — it promotes calm, trust, and mental clarity. Light blues work beautifully in bedrooms and bathrooms. Navy and deep blues add sophistication to living rooms and dining rooms." },
            { type: "heading", text: "Green: Nature's Neutral" },
            { type: "paragraph", text: "Green bridges the gap between warm and cool tones, making it uniquely versatile. It connects us to nature and promotes feelings of balance and restoration. Sage green and olive tones are particularly popular in 2024, working in virtually every room." },
            { type: "heading", text: "Yellow: Energy and Joy" },
            { type: "paragraph", text: "Yellow stimulates the mind and promotes optimism — it's the color of sunshine and happiness. However, bright yellow can be overwhelming in large doses. Use it as an accent color or choose softer, muted yellow tones for larger applications like walls." },
            { type: "heading", text: "Neutrals: The Foundation" },
            { type: "paragraph", text: "White, beige, gray, and greige (gray-beige) form the backbone of most well-designed interiors. They provide a calm backdrop that allows furniture, artwork, and textiles to shine. Warm neutrals (cream, warm white, sand) feel cozy; cool neutrals (pure white, cool gray) feel modern and clean." },
            { type: "heading", text: "Creating a Color Story" },
            { type: "paragraph", text: "Rather than choosing colors room by room in isolation, think about your home as a whole. Choose a 'main' color that flows throughout, then add personality with accent colors in cushions, artwork, and accessories." }
        ]
    },
    {
        id: 8,
        title: "Creating an Outdoor Oasis on a Budget",
        slug: "creating-outdoor-oasis-budget",
        category: "DIY",
        tags: ["outdoor", "garden", "DIY", "budget", "patio"],
        date: "2024-07-15",
        author: "Marcus Chen",
        authorImage: "images/author-marcus.jpg",
        readTime: 6,
        image: "images/outdoor-blog.jpg",
        excerpt: "You don't need a huge budget to create a beautiful outdoor space. With the right approach and a few clever tricks, your balcony or garden can become your favorite room.",
        featured: false,
        content: [
            { type: "paragraph", text: "Your outdoor space — whether a sprawling garden or a tiny balcony — is an extension of your home and deserves as much thoughtful attention as any interior room. The good news is that creating a stunning outdoor area doesn't require a major investment." },
            { type: "heading", text: "Define Your Zones" },
            { type: "paragraph", text: "Just like indoors, outdoor spaces benefit from defined zones. Create a dining area, a lounging area, and a gardening zone. Even in a small space, a simple area rug can visually define different purposes for different parts of your outdoor area." },
            { type: "heading", text: "Start with Seating" },
            { type: "paragraph", text: "Comfortable seating is the heart of any outdoor space. Budget-friendly options abound: look for second-hand rattan or metal furniture, or invest in foldable chairs that store away easily. Add outdoor cushions in weather-resistant fabric for both comfort and color." },
            { type: "heading", text: "Add Layers with Plants" },
            { type: "paragraph", text: "Plants transform outdoor spaces more affordably than any other element. Mix plants at different heights: tall bamboo or ornamental grasses for privacy and structure, mid-height shrubs for color, and trailing plants in hanging baskets for vertical interest." },
            { type: "heading", text: "Lighting Makes Magic" },
            { type: "paragraph", text: "Outdoor lighting extends the usable hours of your outdoor space into the evening and creates a magical atmosphere. Solar-powered fairy lights and lanterns are affordable, easy to install, and use no electricity — a win all around." },
            { type: "heading", text: "DIY Touches" },
            { type: "paragraph", text: "Repurpose old wooden pallets as planters or a simple outdoor sofa base. Upcycle old tins as plant pots. Stencil patterns onto plain concrete paving slabs. These DIY touches add personality and uniqueness that money can't buy." }
        ]
    },
    {
        id: 9,
        title: "5 Bathroom Accessories That Make a Real Difference",
        slug: "bathroom-accessories-that-make-a-difference",
        category: "Decoration",
        tags: ["bathroom", "accessories", "decoration", "spa", "luxury"],
        date: "2024-07-01",
        author: "Ellie Thompson",
        authorImage: "images/author-ellie.jpg",
        readTime: 4,
        image: "images/bathroom-blog.jpg",
        excerpt: "The right accessories can transform your bathroom from a purely functional space into a personal spa retreat. Discover the five accessories that have the biggest impact.",
        featured: false,
        content: [
            { type: "paragraph", text: "The bathroom is often overlooked in home decoration, yet it's a space where you spend significant time each day. The right accessories can make your bathroom feel like a luxury spa without a full renovation." },
            { type: "heading", text: "1. Quality Towels and a Ladder Rack" },
            { type: "paragraph", text: "Nothing signals luxury quite like thick, fluffy towels in a cohesive color palette. Invest in quality cotton or bamboo towels, and display them on a freestanding wooden or metal ladder rack. This simple addition provides both storage and a style statement." },
            { type: "heading", text: "2. A Statement Mirror" },
            { type: "paragraph", text: "The bathroom mirror is one of the most impactful elements in the space. An arched mirror, an oversized round mirror, or a mirror with an interesting frame can completely transform the room's character. It also bounces light, making small bathrooms feel more spacious." },
            { type: "heading", text: "3. Coordinated Ceramic Dispensers" },
            { type: "paragraph", text: "Replace mismatched plastic bottles with a set of coordinated ceramic or glass dispensers for soap, shampoo, and conditioner. This single swap creates an immediate sense of intention and luxury that elevates the entire space." },
            { type: "heading", text: "4. Plants That Thrive in Humidity" },
            { type: "paragraph", text: "Ferns, pothos, orchids, and aloe vera love the humidity of a bathroom. A single well-placed plant can make a bathroom feel like a natural spa. Choose plants proportionate to your space and place them near natural light sources for best results." },
            { type: "heading", text: "5. Candles and a Tray" },
            { type: "paragraph", text: "A small decorative tray holding a few candles, a small plant, and your best toiletries creates a curated, intentional display that makes your bathroom feel like a retreat. Light the candles for bath time and you'll transform your entire experience." }
        ]
    }
];
